logging:
  level: INFO
  loggers:
    com.spotify: DEBUG

server:
  applicationConnectors:
  - type: http 
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

database:
  driverClass: com.mysql.jdbc.Driver
  user: spotify-user
  password: spotify
  url: jdbc:mysql://db:3306/spotify