version: "2.4"

services:
  app:
    build:
      context: .
    ports:
      - 9000:9000
      - 9001:9001
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'spotify'
      MYSQL_USER: 'spotify-user'
      MYSQL_PASSWORD: 'spotify'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'